In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.12769474,  0.12370654,  0.336154  ,  1.07665186,  0.96652584,
       -0.43767235, -0.28820678, -2.65795676, -0.20075476, -0.43605759])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 0.58776474,  0.83911646,  0.59652484, -0.49069274,  0.85553739,
        1.94869278, -0.15334747,  1.59373628, -1.61289125,  0.37781823])

In [10]:
# Binary Functions

np.add(A, B)

array([ 0.71545948,  0.96282299,  0.93267884,  0.58595912,  1.82206323,
        1.51102043, -0.44155425, -1.06422048, -1.81364601, -0.05823936])

In [11]:
np.maximum(A, B)

array([ 0.58776474,  0.83911646,  0.59652484,  1.07665186,  0.96652584,
        1.94869278, -0.15334747,  1.59373628, -0.20075476,  0.37781823])

In [12]:
np.minimum(A, B)

array([ 0.12769474,  0.12370654,  0.336154  , -0.49069274,  0.85553739,
       -0.43767235, -0.28820678, -2.65795676, -1.61289125, -0.43605759])

### Below is really cool stuff

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True